name: Deploy Fullstack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ===== FRONTEND =====
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Next.js
        run: |
          npm install
          npm run build

      - name: Upload Frontend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ".next public package.json next.config.mjs"
          target: "/var/www/frontend/app"

      # ===== BACKEND =====
      - name: Upload Backend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/*"
          target: "/var/www/backend/api"

      - name: Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/backend/api
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi